# Generated by Django 4.2.6 on 2023-12-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
